### ISSUE TITLE
Use operator-sdk for bootstrap [kind/discussion]

### ISSUE THREAD

**Issue by surajnarwade** [halkyonio/api#1]
[kind/discussion]

shall we use operator-sdk to bootstrap the code ?

**Comment by cmoulliard** [comment]
> shall we use operator-sdk to bootstrap the code ?

I don't think that such discussion should take place here as the purpose the of this project is to manage outside of the `component-operator`, the Spec/API that the operator, odo, and even Che could use to describe a Component. 

FYI: the component-operator project has been generated using operator-sdk 0.7.0 and migrated to version 0.1.
